### ISSUE TITLE
Filters with codedocs.xyz

### ISSUE THREAD

**Issue by jcheron** [AbcAeffchen/doxygen-php-filters#5]
Is it possible to use filters with codedocs.xyz (for doc-CI) ?
I tried to configure it in the **.codedocs** file :
`INPUT_FILTER = path/to/filter.php`

But there are no results with traits.php

**Comment by AbcAeffchen** [comment]
I cannot tell if this is possible. But if it is, you need to set `INPUT_FILTER` to `php path/to/filter.php`. But this only works if php is in `PATH`. If it is not, you need to replace `php` by the path to the PHP-executable.

Let me know if this work.

**Comment by jcheron** [comment]
I tried several possibilities : 
  * INPUT_FILTER = path/to/filter.php
  * INPUT_FILTER = php path/to/filter.php

I don't know if php is accessible on codedocs.xyz
Apparently, there is no way to contact codedocs.xyz to ask them...
Thank you very much for your reply, I keep you informed.

**Comment by AbcAeffchen** [comment]
I had a quick look at the codedocs.xyz documentation on https://github.com/CodeDocs/CodeDocs/wiki

They say only a subset of options is whitelisted and `INPUT_FILTER` seems not to be one of them.

`INPUT_FILTER` is  basically a preprocessor. So if it is not supported by codedocs.xyz you can do the preprocessing your self and upload the "sanitized" php files so a docu repository or something like that.

**Comment by jcheron** [comment]
Yes, it is a solution
Thank you
But we lose a little spirit "Continuous integration"

**Comment by AbcAeffchen** [comment]
That is true. Maybe you can build your documentation automatically by a script that triggers after a push to GitHub. But this seems to be a little work. Maybe you can use Jenkins or something like that.
